package SpaceEvaders.Systems.EventsSystem;


public enum EventType {
    SHOOT,
    PLAYER_HIT,
    ENEMY_HIT,
    PLAYER_DESTROYED,
    ENEMY_DESTROYED,
    PLAYER_REPLENISH_HEALTH,
    SPAWN_HEALTH_POWERUP,
    SPAWN_BULLET_POWERUP,
    BULLET_POWERUP_COLLECTED,
    BULLET_POWERUP_EXPIRED,
    PAUSED,
    RESUME,
    PLAY,
    STOP,
    EXIT,
}
